const Icons = {
  iconBackButton: require('../assets/icons/backArrowIcon.svg'),
  infoAuth: require('../assets/icons/infoAuth.svg'),
  home: require('../assets/icons/home.svg'),
  mail: require('../assets/icons/mail.svg'),
  search: require('../assets/icons/search.svg'),
  avtar: require('../assets/icons/user.svg'),
  plus: require('../assets/icons/add.svg'),
  timeHistory: require('../assets/icons/time_history.svg'),
  messageIcon: require('../assets/icons/message-icon.png'),
  userIcon: require('../assets/icons/user-icon.png'),
  privacyIcon: require('../assets/icons/privacy-icon.png'),
  favariteIcon: require('../assets/icons/favotite-icon.png'),
  zowperIcon: require('../assets/icons/zwoper-icon.png'),
  inviteIcon: require('../assets/icons/invite-icon.png'),
  logoutIcon: require('../assets/icons/logout-icon.png'),
  optionIcon: require('../assets/icons/option-icon.png'),
  imageUploadIcon: require('../assets/icons/image-upload.png'),
  plusIcon: require('../assets/icons/plus-icon.png'),
  plusCircleOutline: require('../assets/icons/plus-circle-outline.svg'),
  leftArrowIcon: require('../assets/icons/left-arrow-icon.png'),
  mapPinIcon: require('../assets/icons/map-pin.png'),
  searchIcon: require('../assets/icons/search-icon.png'),
  editIcon: require('../assets/icons/edit-icon.png'),
  closeIcon: require('../assets/icons/close-icon.png'),
  redWatch: require('../assets/icons/red-watch-icon.png'),
  greenWatch: require('../assets/icons/green-watch-icon.png'),
  greenBell: require('../assets/icons/green-bell-icon.png'),
  yellowBell: require('../assets/icons/yellow-bell-icon.png'),
  redBell: require('../assets/icons/red-bell-icon.png'),
  greenEnvelop: require('../assets/icons/green-envelop-icon.png'),
  greenMessage: require('../assets/icons/green-message-icon.png'),
};

export default Icons;
